/* USER CODE BEGIN Header */
/**
  ******************************************************************************
  * @file           : main.h
  * @brief          : Header for main.c file.
  *                   This file contains the common defines of the application.
  ******************************************************************************
  * @attention
  *
  * Copyright (c) 2024 STMicroelectronics.
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  *
  ******************************************************************************
  */
/* USER CODE END Header */

/* Define to prevent recursive inclusion -------------------------------------*/
#ifndef __MAIN_H
#define __MAIN_H

#ifdef __cplusplus
extern "C" {
#endif

/* Includes ------------------------------------------------------------------*/
#include "stm32f1xx_hal.h"

/* Private includes ----------------------------------------------------------*/
/* USER CODE BEGIN Includes */

/* USER CODE END Includes */

/* Exported types ------------------------------------------------------------*/
/* USER CODE BEGIN ET */

/* USER CODE END ET */

/* Exported constants --------------------------------------------------------*/
/* USER CODE BEGIN EC */

/* ============================================================================
 *  COMMUNICATION / ACQUISITION MODE CONFIGURATION
 * ============================================================================
 *  Set the flags below to 1 to enable DMA mode, or 0 for Interrupt (IT) mode.
 *  Only ONE mode should be active per peripheral -- the preprocessor
 *  (#if / #else) in main.c automatically strips out the unused mode's code
 *  at compile time, so you do NOT need to manually comment code in and out.
 *
 *  UART_USE_DMA
 *      1 -> USART3 RX & TX use DMA (HAL_UARTEx_ReceiveToIdle_DMA /
 *           HAL_UART_Transmit_DMA)
 *      0 -> USART3 RX & TX use Interrupt (HAL_UART_Receive_IT /
 *           HAL_UART_Transmit_IT)
 *
 *      IMPORTANT NOTE when choosing UART_USE_DMA = 1:
 *      This CubeMX project originally only generated DMA for ADC1. For UART
 *      DMA mode to work, open the .ioc file, enable the DMA Request for
 *      USART3_RX (and USART3_TX if you also want TX via DMA) on USART3's
 *      "DMA Settings" tab, then regenerate the code. CubeMX will then
 *      automatically create and link the "hdma_usart3_rx" handle in
 *      usart.c / stm32f1xx_hal_msp.c, ready to be used in main.c.
 *
 *  ADC_USE_DMA
 *      1 -> ADC1 uses DMA (HAL_ADC_Start_DMA)      -> already ready to go,
 *           since DMA for ADC1 was already generated by CubeMX (hdma_adc1)
 *      0 -> ADC1 uses Interrupt (HAL_ADC_Start_IT)
 * ============================================================================ */
#define UART_USE_DMA    0   /* 0 = Interrupt (default) | 1 = DMA  */
#define ADC_USE_DMA     1   /* 0 = Interrupt           | 1 = DMA (default) */

/* USER CODE END EC */

/* Exported macro ------------------------------------------------------------*/
/* USER CODE BEGIN EM */

/* USER CODE END EM */

void HAL_TIM_MspPostInit(TIM_HandleTypeDef *htim);

/* Exported functions prototypes ---------------------------------------------*/
void Error_Handler(void);

/* USER CODE BEGIN EFP */

/* USER CODE END EFP */

/* Private defines -----------------------------------------------------------*/
#define RELAY_Pin           GPIO_PIN_5
#define RELAY_GPIO_Port     GPIOA

/* USER CODE BEGIN Private defines */

/* UART command-buffer sizing (used in main.c for RX/TX buffers) */
#define RX_BUFFER_SIZE      20
#define TX_BUFFER_SIZE      20

/* USER CODE END Private defines */

#ifdef __cplusplus
}
#endif

#endif /* __MAIN_H */
